use std::time::SystemTime;

use super::external_type::*;
use core_graphics::event::CGKeyCode;
use serde::{Deserialize, Serialize};

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Key {
    /// Alt key on Linux and Windows (option key on macOS)
    Alt,
    AltGr,
    Backspace,
    CapsLock,
    ControlLeft,
    ControlRight,
    Delete,
    DownArrow,
    End,
    Escape,
    F1,
    F10,
    F11,
    F12,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    Home,
    LeftArrow,
    /// also known as "windows", "super", and "command"
    MetaLeft,
    /// also known as "windows", "super", and "command"
    MetaRight,
    PageDown,
    PageUp,
    Return,
    RightArrow,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    UpArrow,
    PrintScreen,
    ScrollLock,
    Pause,
    NumLock,
    BackQuote,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    Minus,
    Equal,
    KeyQ,
    KeyW,
    KeyE,
    KeyR,
    KeyT,
    KeyY,
    KeyU,
    KeyI,
    KeyO,
    KeyP,
    LeftBracket,
    RightBracket,
    KeyA,
    KeyS,
    KeyD,
    KeyF,
    KeyG,
    KeyH,
    KeyJ,
    KeyK,
    KeyL,
    SemiColon,
    Quote,
    BackSlash,
    IntlBackslash,
    KeyZ,
    KeyX,
    KeyC,
    KeyV,
    KeyB,
    KeyN,
    KeyM,
    Comma,
    Dot,
    Slash,
    Insert,
    KpReturn,
    KpMinus,
    KpPlus,
    KpMultiply,
    KpDivide,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDelete,
    Function,
    Unknown(u32),
}

impl From<CGKeyCode> for Key {
    fn from(code: CGKeyCode) -> Self {
        match code {
            ALT => Key::Alt,
            ALT_GR => Key::AltGr,
            BACKSPACE => Key::Backspace,
            CAPS_LOCK => Key::CapsLock,
            CONTROL_LEFT => Key::ControlLeft,
            CONTROL_RIGHT => Key::ControlRight,
            DOWN_ARROW => Key::DownArrow,
            ESCAPE => Key::Escape,
            F1 => Key::F1,
            F10 => Key::F10,
            F11 => Key::F11,
            F12 => Key::F12,
            F2 => Key::F2,
            F3 => Key::F3,
            F4 => Key::F4,
            F5 => Key::F5,
            F6 => Key::F6,
            F7 => Key::F7,
            F8 => Key::F8,
            F9 => Key::F9,
            LEFT_ARROW => Key::LeftArrow,
            META_LEFT => Key::MetaLeft,
            META_RIGHT => Key::MetaRight,
            RETURN => Key::Return,
            RIGHT_ARROW => Key::RightArrow,
            SHIFT_LEFT => Key::ShiftLeft,
            SHIFT_RIGHT => Key::ShiftRight,
            SPACE => Key::Space,
            TAB => Key::Tab,
            UP_ARROW => Key::UpArrow,
            BACK_QUOTE => Key::BackQuote,
            NUM1 => Key::Num1,
            NUM2 => Key::Num2,
            NUM3 => Key::Num3,
            NUM4 => Key::Num4,
            NUM5 => Key::Num5,
            NUM6 => Key::Num6,
            NUM7 => Key::Num7,
            NUM8 => Key::Num8,
            NUM9 => Key::Num9,
            NUM0 => Key::Num0,
            MINUS => Key::Minus,
            EQUAL => Key::Equal,
            KEY_Q => Key::KeyQ,
            KEY_W => Key::KeyW,
            KEY_E => Key::KeyE,
            KEY_R => Key::KeyR,
            KEY_T => Key::KeyT,
            KEY_Y => Key::KeyY,
            KEY_U => Key::KeyU,
            KEY_I => Key::KeyI,
            KEY_O => Key::KeyO,
            KEY_P => Key::KeyP,
            LEFT_BRACKET => Key::LeftBracket,
            RIGHT_BRACKET => Key::RightBracket,
            KEY_A => Key::KeyA,
            KEY_S => Key::KeyS,
            KEY_D => Key::KeyD,
            KEY_F => Key::KeyF,
            KEY_G => Key::KeyG,
            KEY_H => Key::KeyH,
            KEY_J => Key::KeyJ,
            KEY_K => Key::KeyK,
            KEY_L => Key::KeyL,
            SEMI_COLON => Key::SemiColon,
            QUOTE => Key::Quote,
            BACK_SLASH => Key::BackSlash,
            KEY_Z => Key::KeyZ,
            KEY_X => Key::KeyX,
            KEY_C => Key::KeyC,
            KEY_V => Key::KeyV,
            KEY_B => Key::KeyB,
            KEY_N => Key::KeyN,
            KEY_M => Key::KeyM,
            COMMA => Key::Comma,
            DOT => Key::Dot,
            SLASH => Key::Slash,
            FUNCTION => Key::Function,
            code => Key::Unknown(code.into()),
        }
    }
}

/// In order to manage different OSs, the current EventType choices are a mix and
/// match to account for all possible events.
#[derive(Debug, Copy, Clone, PartialEq, Serialize, Deserialize)]
pub enum EventType {
    /// The keys correspond to a standard qwerty layout, they don't correspond
    /// To the actual letter a user would use, that requires some layout logic to be added.
    KeyPress(Key),
    KeyRelease(Key),
}

/// When events arrive from the OS they get some additional information added from
/// EventType, which is the time when this event was received, and the name Option
/// which contains what characters should be emmitted from that event. This relies
/// on the OS layout and keyboard state machinery.
/// Caveat: Dead keys don't function on Linux(X11) yet. You will receive None for
/// a dead key, and the raw letter instead of accentuated letter.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Event {
    pub time: SystemTime,
    pub name: Option<String>,
    pub event_type: EventType,
}
